# For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test localization

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["*"]

jobs:

  Ubuntu:
    runs-on: ubuntu-latest

    steps:

      - name: Change locale to ru_RU.UTF-8
        run: |
          sudo apt-get update && sudo apt-get install -y locales
          sudo locale-gen ru_RU.UTF-8
          export LANG=ru_RU.UTF-8
          export LC_ALL=ru_RU.UTF-8

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          dotnet-quality: "ga"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Test indicators
        run: pytest -m "localization"

  Windows:
    runs-on: windows-latest

    steps:

      - name: Change locale to ru_RU.UTF-8
        shell: pwsh
        run: |
          Set-WinSystemLocale ru-RU
          Set-WinUserLanguageList ru-RU -Force
          $env:LANG = 'ru_RU.UTF-8'
          $env:LC_ALL = 'ru_RU.UTF-8'

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          dotnet-quality: "ga"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Test indicators
        run: pytest -m "localization"

  macOS:
    runs-on: macos-latest

    steps:

      - name: Change locale to ru_RU.UTF-8
        run: |
          sudo languagesetup -langspec ru
          export LANG=ru_RU.UTF-8
          export LC_ALL=ru_RU.UTF-8

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          dotnet-quality: "ga"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Test indicators
        run: pytest -m "localization"
