# For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test localization

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["*"]

jobs:

  localization:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        locale: ['fr_FR.UTF-8', 'de_DE.UTF-8']
        python-version: ['3.8', '3.12']

    name: "${{ matrix.locale }} | Py ${{ matrix.python-version }} [${{ matrix.os }}]"
    runs-on: ${{ matrix.os }}

    steps:

      - name: Change locale to ${{ matrix.locale }}
        run: |
          sudo apt-get update && sudo apt-get install -y locales
          sudo locale-gen ${{ matrix.locale }}
          sudo update-locale LANG=${{ matrix.locale }}
          export LANG=${{ matrix.locale }}
          export LC_ALL=${{ matrix.locale }}

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          dotnet-quality: "ga"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Setup Locale (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo locale-gen ${{ matrix.locale }}
          sudo update-locale LANG=${{ matrix.locale }}

      - name: Set macOS locale to ${{ matrix.locale }}
        if: runner.os == 'macOS'
        run: |
          sudo languagesetup -langspec ${{ matrix.locale }}
          export LANG=${{ matrix.locale }}
          export LC_ALL=${{ matrix.locale }}

      - name: Set Windows locale to ${{ matrix.locale }}
        if: runner.os == 'Windows'
        run: |
          chcp 65001
          set PYTHONIOENCODING=utf-8
          set LANG=${{ matrix.locale }}

      - name: Set Windows locale to ${{ matrix.locale }} (PS)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Set-WinSystemLocale ${{ matrix.locale }}
          Set-WinUserLanguageList ${{ matrix.locale }} -Force
          $env:LANG = '${{ matrix.locale }}'
          $env:LC_ALL = '${{ matrix.locale }}'
          $env:PYTHONIOENCODING = 'utf-8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Test indicators
        env:
          LANG: ${{ matrix.locale }}
          LC_ALL: ${{ matrix.locale }}
          PYTHONIOENCODING: utf-8
        run: pytest -m "localization" -vr A tests --junitxml=test-results.xml

      - name: Post test summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: test-results.xml
