# For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test localization

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  localization:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # macOS removed due to locale issues
        locale: [
          'fr_FR.UTF-8',    # Uses comma as decimal separator
          'ru_RU.UTF-8'     # Uses comma as decimal, space as thousands
        ]
        python-version: ['3.12']

    name: "Py${{ matrix.python-version }} @ ${{ matrix.locale }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    env:
      PYTHONPATH: ${{ github.workspace }}
      LC_NUMERIC: ${{ matrix.locale }}
      LC_MONETARY: ${{ matrix.locale }}
      LANG: ${{ matrix.locale }}
      LC_ALL: ${{ matrix.locale }}
      PYTHONIOENCODING: utf-8

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          dotnet-quality: "ga"

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Configure Linux locale
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update && sudo apt-get install -y locales
          LOCALE_NAME=$(echo "${{ matrix.locale }}" | cut -d. -f1)
          sudo locale-gen ${{ matrix.locale }}
          sudo update-locale LANG=${{ matrix.locale }} LC_ALL=${{ matrix.locale }}
          locale

      - name: Configure Windows locale
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $locale = "${{ matrix.locale }}".Split('.')[0].Replace('_', '-')
          [System.Threading.Thread]::CurrentThread.CurrentCulture = [System.Globalization.CultureInfo]::GetCultureInfo($locale)
          [System.Threading.Thread]::CurrentThread.CurrentUICulture = [System.Globalization.CultureInfo]::GetCultureInfo($locale)

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Verify locale
        run: |
          python -c "import locale; print(f'Locale: {locale.getlocale()}')"
          python -c "import locale; print(f'Currency: {locale.currency(1234.56)}')"
          python -c "import locale; print(f'Number: {locale.format_string(\"%.2f\", 1234.56)}')"

      - name: Run locale tests
        run: pytest -m "localization" -vr A tests --junitxml=test-results.xml

      - uses: test-summary/action@v2
        if: always()
        with:
          paths: test-results.xml
